#!/usr/bin/env python3

import logging
import os
import os.path

import cli
from scaler import Scaler
from bulk_applier import BulkApplier

def destination(filename: str) -> str:
  return os.path.join(
    os.path.dirname(filename),
    'scaled' + os.path.basename(filename))

args = cli.get_args()

logging.debug(f'Parsed args: {args}')

scaler = Scaler(factor=args.scale)

ba = BulkApplier(
  apply=scaler.scale,
  ffilter=lambda x: os.path.basename(x) == args.name,
  rename=destination
)

ba.bulk_apply(top=args.top)