#!/usr/bin/env python3

import logging
import os
import os.path

import cli
from scaler import Scaler

def destination(filename: str) -> str:
  return os.path.join(
    os.path.dirname(filename),
    'scaled' + os.path.basename(filename))

args = cli.get_args()

if args.verbose:
  logging.basicConfig(level=logging.DEBUG)
elif args.quiet:
  logging.basicConfig(level=logging.WARN)
else:
  logging.basicConfig(level=logging.INFO)

logging.debug(f'Parsed args: {args}')

scaler = Scaler(factor=args.scale)

logging.info('Finding input files...')

targets = [
  (infile, destination(infile))
  for infile in [
    os.path.join(dirpath, args.name)
    for dirpath, _, filenames
    in os.walk(top=args.top)
    if args.name in filenames
  ]
]

logging.info(f'Found {len(targets)} input file(s)')
logging.debug(f'Input/Output file pairs: {targets}')

for source, dest in targets:
  scaler.scale(source, dest)